import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class ExceptionTest {

	public static void main(String[] args) {
		
		Scanner sc = new Scanner(System.in);
		System.out.println("파일 이름 입력 : ");
		String filename = sc.next();
		try {
			File f = CreateFile(filename);
			System.out.println(f.getName() + "파일 생성");
		}catch(IOException e) {
			System.out.println("파일 생성이 안됐습니다.");
		}catch(Exception e) {
//			System.out.println("파일의 이름을 확인하세요.");
			System.out.println(e.getMessage());
		}
	}
	
		static File CreateFile(String filename) throws IOException , Exception {
			File f = null;
			
			if(filename == null || filename.equals("")) {
				throw new Exception("파일의 이름이 유효하지 않습니다.");
//					filename = "제목없음.txt";
			}
				f = new File(filename);
				f.createNewFile();
//			}catch(IOException e) {
//				System.out.println("파일생성이 안되었습니다.");
//			}catch(Exception e) {				
//				filename = "제목없음.txt";
//				try {
//					f = new File(filename);
//					f.createNewFile();
//				}catch(IOException el) {
//					System.out.println("파일생성이 안되었습니다.");
//			}finally {
//				return f;
//			}
				return f;	
			}

}


		

				
//			}catch(Exception e) {
//			}finally {
////				createNewFile(f);
//				return f;
//			}

			
	
		
//	static void createNewFile(File f){
//		try {
//		f.createNewFile();
//		}catch(IOException e) {
//			System.out.println("파일 생성이 안되었습니다.");
//		}
//	}
		

